# -- coding: utf-8 --
"""Food_Trip_Planner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcNTPvw_5UFJ49aD1KXb6grhP7Zevcc_
"""

# Global UUID is generated for agent and task
import uuid

AGENT_UUID = uuid.uuid4()
TASK_UUID = uuid.uuid4()

from julep import Client
import os

JULEP_API_KEY = 'JULEP_API_KEY'

# Create a Julep client
client = Client(api_key=JULEP_API_KEY, environment="production")

# Defining the agent
name = "City Foodie Tour Agent"
about = "Plans weather-aware foodie tours per city"

# Create the agent
agent = client.agents.create_or_update(
    agent_id=AGENT_UUID,
    name=name,
    about=about,
    model="gpt-4o",
)
print("✅ Agent created with ID:", agent.id)



import yaml

brave_api_key ="BRAVE_API_KEY"
openweathermap_api_key = "OPENWEATHERMAP_API_KEY"
task_def = yaml.safe_load(f"""
# yaml-language-server: $schema=https://raw.githubusercontent.com/julep-ai/julep/refs/heads/dev/schemas/create_task_request.json
name: City Foodie Tour Planner
description: Plans weather-aware foodie tours per city using real-time data
input_schema:
  type: object
  properties:
    locations:
      type: array
      items:
        type: string
      description: The locations to search for.

tools:
- name: weather
  type: integration
  integration:
    provider: weather
    setup:
      openweathermap_api_key: {openweathermap_api_key}
- name: internet_search
  type: integration
  integration:
    provider: brave
    setup:
      brave_api_key: {brave_api_key}

main:
# Step 0: Fetch weather data for each location
- over: $ steps[0].input.locations
  map:
    tool: weather
    arguments:
      location: $ _
  parallelism: 5

# Step 1: Brave Search for finding iconic local dishes for each city
- over: $ steps[0].input.locations
  map:
    tool: internet_search
    arguments:
      query: $ 'most iconic foods are ' + _
  parallelism: 5

# Step 2: Combine data
- evaluate:
    zipped: |-
      $ list(
        zip(
          steps[0].input.locations,
          [output['result'] for output in steps[0].output],
          steps[1].output
        )
      )

# Step 3: Generate itineraries
- over: $ _['zipped']
  parallelism: 3
  map:
    prompt:
    - role: system
      content: >-
        You are a travel expert creating a 3-day itinerary.
        For each location, you'll receive:
        - Weather conditions
        - Top tourist attractions
        Create a plan with:
        1. Morning activity
        2. Afternoon excursion
        3. Evening experience
        4. Fun local facts
    - role: user
      content: >-
        Location: "{{_[0]}}"
        Weather: "{{_[1]}}"
        Attractions: "{{_[2]}}"
    unwrap: true

# Step 4: Format final output
- evaluate:
    final_plan: |-
      $ '\\n---------------\\n'.join([activity for activity in _])

""")

# Verify the parsed structure
print("✅ Task definition loaded successfully!")
print("First 7 workflow steps:", task_def['main'][:7])


# creating the task object
task = client.tasks.create_or_update(
    task_id=TASK_UUID,
    agent_id=AGENT_UUID,
    **task_def
)

execution = client.executions.create(
    task_id=task.id,
    input={
         "locations": ["Indore", "Mumbai"]
    }
)

print("Started an execution. Execution ID:", execution.id)

import time

execution = client.executions.get(execution.id)

while execution.status != "succeeded":
    time.sleep(5)
    execution = client.executions.get(execution.id)
    print("Execution status: ", execution.status)
    print("Execution output:", execution.output)
    print("-"*5)

execution = client.executions.get(execution.id)

if 'final_plan' in execution.output:
    print(execution.output['final_plan'])
else:
    print(execution.output)


# Lists all the task steps that have been executed up to this point in time
transitions = client.executions.transitions.list(execution_id=execution.id).items

# Transitions are retrieved in reverse chronological order
for transition in reversed(transitions):
    print("Transition type: ", transition.type)
    print("Transition output: ", transition.output)
    print("-"*50)
